module render.reflections;
import std;
import toy;

import <vulkan_config.h>;

namespace rd::refl {

#define CASE(x)                                                                                    \
  case x:                                                                                          \
    return #x
auto imageLayout(VkImageLayout image_layout) -> std::string_view {
  switch (image_layout) {
    CASE(VK_IMAGE_LAYOUT_UNDEFINED);
    CASE(VK_IMAGE_LAYOUT_PREINITIALIZED);
    CASE(VK_IMAGE_LAYOUT_COLOR_ATTACHMENT_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_DEPTH_STENCIL_ATTACHMENT_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_DEPTH_STENCIL_READ_ONLY_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_SHADER_READ_ONLY_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_TRANSFER_SRC_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_TRANSFER_DST_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_DEPTH_READ_ONLY_STENCIL_ATTACHMENT_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_DEPTH_ATTACHMENT_STENCIL_READ_ONLY_OPTIMAL);
    CASE(VK_IMAGE_LAYOUT_PRESENT_SRC_KHR);
  default:
    toy::throwf("unknown VkImageLayout: {}", static_cast<size_t>(image_layout));
  }
}

auto stageFlag(VkPipelineStageFlagBits2 stage) -> std::string_view {
  switch (stage) {
    CASE(VK_PIPELINE_STAGE_VERTEX_INPUT_BIT);
    CASE(VK_PIPELINE_STAGE_VERTEX_SHADER_BIT);
    CASE(VK_PIPELINE_STAGE_FRAGMENT_SHADER_BIT);
    CASE(VK_PIPELINE_STAGE_TRANSFER_BIT);
    CASE(VK_PIPELINE_STAGE_BOTTOM_OF_PIPE_BIT);
    CASE(VK_PIPELINE_STAGE_TOP_OF_PIPE_BIT);
    CASE(VK_PIPELINE_STAGE_ALL_COMMANDS_BIT);
    CASE(VK_PIPELINE_STAGE_COLOR_ATTACHMENT_OUTPUT_BIT);
    CASE(VK_PIPELINE_STAGE_EARLY_FRAGMENT_TESTS_BIT);
    CASE(VK_PIPELINE_STAGE_LATE_FRAGMENT_TESTS_BIT);
    CASE(VK_PIPELINE_STAGE_NONE);
  default:
    toy::throwf("unknown VkPipelineStageFlagBits2: {}", static_cast<size_t>(stage));
  }
}

auto accessFlag(VkAccessFlagBits2 access) -> std::string_view {
  switch (access) {
    CASE(VK_ACCESS_INDEX_READ_BIT);
    CASE(VK_ACCESS_VERTEX_ATTRIBUTE_READ_BIT);
    CASE(VK_ACCESS_UNIFORM_READ_BIT);
    CASE(VK_ACCESS_INPUT_ATTACHMENT_READ_BIT);
    CASE(VK_ACCESS_SHADER_READ_BIT);
    CASE(VK_ACCESS_SHADER_WRITE_BIT);
    CASE(VK_ACCESS_COLOR_ATTACHMENT_READ_BIT);
    CASE(VK_ACCESS_COLOR_ATTACHMENT_WRITE_BIT);
    CASE(VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_READ_BIT);
    CASE(VK_ACCESS_DEPTH_STENCIL_ATTACHMENT_WRITE_BIT);
    CASE(VK_ACCESS_TRANSFER_READ_BIT);
    CASE(VK_ACCESS_TRANSFER_WRITE_BIT);
    CASE(VK_ACCESS_NONE);
  default:
    toy::throwf("unknown VkAccessFlagBits2: {}", static_cast<size_t>(access));
  };
}

auto format(VkFormat format) -> std::string_view {
  switch (format) {
    CASE(VK_FORMAT_UNDEFINED);
    CASE(VK_FORMAT_R4G4_UNORM_PACK8);
    CASE(VK_FORMAT_R4G4B4A4_UNORM_PACK16);
    CASE(VK_FORMAT_B4G4R4A4_UNORM_PACK16);
    CASE(VK_FORMAT_R5G6B5_UNORM_PACK16);
    CASE(VK_FORMAT_B5G6R5_UNORM_PACK16);
    CASE(VK_FORMAT_R5G5B5A1_UNORM_PACK16);
    CASE(VK_FORMAT_B5G5R5A1_UNORM_PACK16);
    CASE(VK_FORMAT_A1R5G5B5_UNORM_PACK16);
    CASE(VK_FORMAT_R8_UNORM);
    CASE(VK_FORMAT_R8_SNORM);
    CASE(VK_FORMAT_R8_USCALED);
    CASE(VK_FORMAT_R8_SSCALED);
    CASE(VK_FORMAT_R8_UINT);
    CASE(VK_FORMAT_R8_SINT);
    CASE(VK_FORMAT_R8_SRGB);
    CASE(VK_FORMAT_R8G8_UNORM);
    CASE(VK_FORMAT_R8G8_SNORM);
    CASE(VK_FORMAT_R8G8_USCALED);
    CASE(VK_FORMAT_R8G8_SSCALED);
    CASE(VK_FORMAT_R8G8_UINT);
    CASE(VK_FORMAT_R8G8_SINT);
    CASE(VK_FORMAT_R8G8_SRGB);
    CASE(VK_FORMAT_R8G8B8_UNORM);
    CASE(VK_FORMAT_R8G8B8_SNORM);
    CASE(VK_FORMAT_R8G8B8_USCALED);
    CASE(VK_FORMAT_R8G8B8_SSCALED);
    CASE(VK_FORMAT_R8G8B8_UINT);
    CASE(VK_FORMAT_R8G8B8_SINT);
    CASE(VK_FORMAT_R8G8B8_SRGB);
    CASE(VK_FORMAT_B8G8R8_UNORM);
    CASE(VK_FORMAT_B8G8R8_SNORM);
    CASE(VK_FORMAT_B8G8R8_USCALED);
    CASE(VK_FORMAT_B8G8R8_SSCALED);
    CASE(VK_FORMAT_B8G8R8_UINT);
    CASE(VK_FORMAT_B8G8R8_SINT);
    CASE(VK_FORMAT_B8G8R8_SRGB);
    CASE(VK_FORMAT_R8G8B8A8_UNORM);
    CASE(VK_FORMAT_R8G8B8A8_SNORM);
    CASE(VK_FORMAT_R8G8B8A8_USCALED);
    CASE(VK_FORMAT_R8G8B8A8_SSCALED);
    CASE(VK_FORMAT_R8G8B8A8_UINT);
    CASE(VK_FORMAT_R8G8B8A8_SINT);
    CASE(VK_FORMAT_R8G8B8A8_SRGB);
    CASE(VK_FORMAT_B8G8R8A8_UNORM);
    CASE(VK_FORMAT_B8G8R8A8_SNORM);
    CASE(VK_FORMAT_B8G8R8A8_USCALED);
    CASE(VK_FORMAT_B8G8R8A8_SSCALED);
    CASE(VK_FORMAT_B8G8R8A8_UINT);
    CASE(VK_FORMAT_B8G8R8A8_SINT);
    CASE(VK_FORMAT_B8G8R8A8_SRGB);
    CASE(VK_FORMAT_A8B8G8R8_UNORM_PACK32);
    CASE(VK_FORMAT_A8B8G8R8_SNORM_PACK32);
    CASE(VK_FORMAT_A8B8G8R8_USCALED_PACK32);
    CASE(VK_FORMAT_A8B8G8R8_SSCALED_PACK32);
    CASE(VK_FORMAT_A8B8G8R8_UINT_PACK32);
    CASE(VK_FORMAT_A8B8G8R8_SINT_PACK32);
    CASE(VK_FORMAT_A8B8G8R8_SRGB_PACK32);
    CASE(VK_FORMAT_A2R10G10B10_UNORM_PACK32);
    CASE(VK_FORMAT_A2R10G10B10_SNORM_PACK32);
    CASE(VK_FORMAT_A2R10G10B10_USCALED_PACK32);
    CASE(VK_FORMAT_A2R10G10B10_SSCALED_PACK32);
    CASE(VK_FORMAT_A2R10G10B10_UINT_PACK32);
    CASE(VK_FORMAT_A2R10G10B10_SINT_PACK32);
    CASE(VK_FORMAT_A2B10G10R10_UNORM_PACK32);
    CASE(VK_FORMAT_A2B10G10R10_SNORM_PACK32);
    CASE(VK_FORMAT_A2B10G10R10_USCALED_PACK32);
    CASE(VK_FORMAT_A2B10G10R10_SSCALED_PACK32);
    CASE(VK_FORMAT_A2B10G10R10_UINT_PACK32);
    CASE(VK_FORMAT_A2B10G10R10_SINT_PACK32);
    CASE(VK_FORMAT_R16_UNORM);
    CASE(VK_FORMAT_R16_SNORM);
    CASE(VK_FORMAT_R16_USCALED);
    CASE(VK_FORMAT_R16_SSCALED);
    CASE(VK_FORMAT_R16_UINT);
    CASE(VK_FORMAT_R16_SINT);
    CASE(VK_FORMAT_R16_SFLOAT);
    CASE(VK_FORMAT_R16G16_UNORM);
    CASE(VK_FORMAT_R16G16_SNORM);
    CASE(VK_FORMAT_R16G16_USCALED);
    CASE(VK_FORMAT_R16G16_SSCALED);
    CASE(VK_FORMAT_R16G16_UINT);
    CASE(VK_FORMAT_R16G16_SINT);
    CASE(VK_FORMAT_R16G16_SFLOAT);
    CASE(VK_FORMAT_R16G16B16_UNORM);
    CASE(VK_FORMAT_R16G16B16_SNORM);
    CASE(VK_FORMAT_R16G16B16_USCALED);
    CASE(VK_FORMAT_R16G16B16_SSCALED);
    CASE(VK_FORMAT_R16G16B16_UINT);
    CASE(VK_FORMAT_R16G16B16_SINT);
    CASE(VK_FORMAT_R16G16B16_SFLOAT);
    CASE(VK_FORMAT_R16G16B16A16_UNORM);
    CASE(VK_FORMAT_R16G16B16A16_SNORM);
    CASE(VK_FORMAT_R16G16B16A16_USCALED);
    CASE(VK_FORMAT_R16G16B16A16_SSCALED);
    CASE(VK_FORMAT_R16G16B16A16_UINT);
    CASE(VK_FORMAT_R16G16B16A16_SINT);
    CASE(VK_FORMAT_R16G16B16A16_SFLOAT);
    CASE(VK_FORMAT_R32_UINT);
    CASE(VK_FORMAT_R32_SINT);
    CASE(VK_FORMAT_R32_SFLOAT);
    CASE(VK_FORMAT_R32G32_UINT);
    CASE(VK_FORMAT_R32G32_SINT);
    CASE(VK_FORMAT_R32G32_SFLOAT);
    CASE(VK_FORMAT_R32G32B32_UINT);
    CASE(VK_FORMAT_R32G32B32_SINT);
    CASE(VK_FORMAT_R32G32B32_SFLOAT);
    CASE(VK_FORMAT_R32G32B32A32_UINT);
    CASE(VK_FORMAT_R32G32B32A32_SINT);
    CASE(VK_FORMAT_R32G32B32A32_SFLOAT);
    CASE(VK_FORMAT_R64_UINT);
    CASE(VK_FORMAT_R64_SINT);
    CASE(VK_FORMAT_R64_SFLOAT);
    CASE(VK_FORMAT_R64G64_UINT);
    CASE(VK_FORMAT_R64G64_SINT);
    CASE(VK_FORMAT_R64G64_SFLOAT);
    CASE(VK_FORMAT_R64G64B64_UINT);
    CASE(VK_FORMAT_R64G64B64_SINT);
    CASE(VK_FORMAT_R64G64B64_SFLOAT);
    CASE(VK_FORMAT_R64G64B64A64_UINT);
    CASE(VK_FORMAT_R64G64B64A64_SINT);
    CASE(VK_FORMAT_R64G64B64A64_SFLOAT);
    CASE(VK_FORMAT_B10G11R11_UFLOAT_PACK32);
    CASE(VK_FORMAT_E5B9G9R9_UFLOAT_PACK32);
    CASE(VK_FORMAT_D16_UNORM);
    CASE(VK_FORMAT_X8_D24_UNORM_PACK32);
    CASE(VK_FORMAT_D32_SFLOAT);
    CASE(VK_FORMAT_S8_UINT);
    CASE(VK_FORMAT_D16_UNORM_S8_UINT);
    CASE(VK_FORMAT_D24_UNORM_S8_UINT);
    CASE(VK_FORMAT_D32_SFLOAT_S8_UINT);
    CASE(VK_FORMAT_BC1_RGB_UNORM_BLOCK);
    CASE(VK_FORMAT_BC1_RGB_SRGB_BLOCK);
    CASE(VK_FORMAT_BC1_RGBA_UNORM_BLOCK);
    CASE(VK_FORMAT_BC1_RGBA_SRGB_BLOCK);
    CASE(VK_FORMAT_BC2_UNORM_BLOCK);
    CASE(VK_FORMAT_BC2_SRGB_BLOCK);
    CASE(VK_FORMAT_BC3_UNORM_BLOCK);
    CASE(VK_FORMAT_BC3_SRGB_BLOCK);
    CASE(VK_FORMAT_BC4_UNORM_BLOCK);
    CASE(VK_FORMAT_BC4_SNORM_BLOCK);
    CASE(VK_FORMAT_BC5_UNORM_BLOCK);
    CASE(VK_FORMAT_BC5_SNORM_BLOCK);
    CASE(VK_FORMAT_BC6H_UFLOAT_BLOCK);
    CASE(VK_FORMAT_BC6H_SFLOAT_BLOCK);
    CASE(VK_FORMAT_BC7_UNORM_BLOCK);
    CASE(VK_FORMAT_BC7_SRGB_BLOCK);
    CASE(VK_FORMAT_ETC2_R8G8B8_UNORM_BLOCK);
    CASE(VK_FORMAT_ETC2_R8G8B8_SRGB_BLOCK);
    CASE(VK_FORMAT_ETC2_R8G8B8A1_UNORM_BLOCK);
    CASE(VK_FORMAT_ETC2_R8G8B8A1_SRGB_BLOCK);
    CASE(VK_FORMAT_ETC2_R8G8B8A8_UNORM_BLOCK);
    CASE(VK_FORMAT_ETC2_R8G8B8A8_SRGB_BLOCK);
    CASE(VK_FORMAT_EAC_R11_UNORM_BLOCK);
    CASE(VK_FORMAT_EAC_R11_SNORM_BLOCK);
    CASE(VK_FORMAT_EAC_R11G11_UNORM_BLOCK);
    CASE(VK_FORMAT_EAC_R11G11_SNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_4x4_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_4x4_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_5x4_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_5x4_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_5x5_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_5x5_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_6x5_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_6x5_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_6x6_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_6x6_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_8x5_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_8x5_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_8x6_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_8x6_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_8x8_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_8x8_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_10x5_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_10x5_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_10x6_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_10x6_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_10x8_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_10x8_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_10x10_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_10x10_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_12x10_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_12x10_SRGB_BLOCK);
    CASE(VK_FORMAT_ASTC_12x12_UNORM_BLOCK);
    CASE(VK_FORMAT_ASTC_12x12_SRGB_BLOCK);

  default:
    toy::debugf("error: unknown VkFormat: {}", static_cast<size_t>(format));
    return "unknown";
  }
}

auto colorSpace(VkColorSpaceKHR color_space) -> std::string_view {
  switch (color_space) {
    CASE(VK_COLOR_SPACE_SRGB_NONLINEAR_KHR);
    CASE(VK_COLOR_SPACE_DISPLAY_P3_NONLINEAR_EXT);
    CASE(VK_COLOR_SPACE_EXTENDED_SRGB_LINEAR_EXT);
    CASE(VK_COLOR_SPACE_DISPLAY_P3_LINEAR_EXT);
    CASE(VK_COLOR_SPACE_DCI_P3_NONLINEAR_EXT);
    CASE(VK_COLOR_SPACE_BT709_LINEAR_EXT);
    CASE(VK_COLOR_SPACE_BT709_NONLINEAR_EXT);
    CASE(VK_COLOR_SPACE_BT2020_LINEAR_EXT);
    CASE(VK_COLOR_SPACE_HDR10_ST2084_EXT);
    CASE(VK_COLOR_SPACE_DOLBYVISION_EXT);
    CASE(VK_COLOR_SPACE_HDR10_HLG_EXT);
    CASE(VK_COLOR_SPACE_ADOBERGB_LINEAR_EXT);
    CASE(VK_COLOR_SPACE_ADOBERGB_NONLINEAR_EXT);
    CASE(VK_COLOR_SPACE_PASS_THROUGH_EXT);
    CASE(VK_COLOR_SPACE_EXTENDED_SRGB_NONLINEAR_EXT);
    CASE(VK_COLOR_SPACE_DISPLAY_NATIVE_AMD);
    CASE(VK_COLOR_SPACE_MAX_ENUM_KHR);
  };
}

auto result(VkResult result) -> std::string_view {
  switch (result) {
    CASE(VK_SUCCESS);
    CASE(VK_NOT_READY);
    CASE(VK_TIMEOUT);
    CASE(VK_EVENT_SET);
    CASE(VK_EVENT_RESET);
    CASE(VK_INCOMPLETE);
    CASE(VK_SUBOPTIMAL_KHR);
    CASE(VK_ERROR_OUT_OF_DATE_KHR);
  default:
    toy::throwf("unknown VkResult: {}", static_cast<size_t>(result));
  }
}

auto sampleCount(VkSampleCountFlagBits sample_count) -> std::string_view {
  switch (sample_count) {
    CASE(VK_SAMPLE_COUNT_1_BIT);
    CASE(VK_SAMPLE_COUNT_2_BIT);
    CASE(VK_SAMPLE_COUNT_4_BIT);
    CASE(VK_SAMPLE_COUNT_8_BIT);
    CASE(VK_SAMPLE_COUNT_16_BIT);
    CASE(VK_SAMPLE_COUNT_32_BIT);
    CASE(VK_SAMPLE_COUNT_64_BIT);
  default:
    toy::throwf("unknown VkSampleCountFlagBits: {}", static_cast<size_t>(sample_count));
  }
}

#undef CASE
} // namespace rd::refl